name: Scrape-and-Summarise   # назва воркфлоу, що відобразиться у вкладці Actions

on:
  workflow_dispatch:         # дозволяє запускати вручну кнопкою “Run workflow”
  schedule:
    - cron: '15 02 * * *'    # щодня о 02:15 UTC (05:15 за Києвом)

jobs:
  build:
    runs-on: ubuntu-latest

    # токен GITHUB_TOKEN за замовчанням «read»; потрібно «write», щоб робити git push
    permissions:
      contents: write

    steps:
      # 1. клонувати репозиторій
      - uses: actions/checkout@v4

      # 2. встановити Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. поставити залежності (додайте свої, якщо треба)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests reportlab gdelt

      # 4. запустити ваш скрипт; ключ дістаємо з Secrets
      - name: Run ETL script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/etl.py

      # 5. закомітити й запушити нові JSON / PDF, якщо вони з’явилися
      - name: Commit and push changes
        run: |
          git config user.name  "auto-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/*.json pdf/*.pdf || true
          # робимо коміт — тільки якщо є зміни
          git diff --cached --quiet || git commit -m "auto: update $(date -u +'%F %T')"
          git push
